FROM nginx:1.17.10

COPY sites-enabled/heroku.config /etc/nginx/conf.d/heroku.config
COPY sites-enabled/nginx.conf /etc/nginx/nginx.conf

CMD /bin/bash -c "envsubst '\$PORT' < /etc/nginx/conf.d/heroku.config > /etc/nginx/conf.d/default.conf" && nginx -g 'daemon off;'
