# Generated by Django 2.2.11 on 2020-06-03 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'get_latest_by': 'id', 'ordering': ['-id'], 'verbose_name': 'CompanyEmployer', 'verbose_name_plural': 'CompanyEmployer'},
        ),
        migrations.AlterField(
            model_name='employer',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='last_mod_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last_modified'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='source',
            field=models.CharField(blank=True, max_length=100, verbose_name='source'),
        ),
    ]
