# Generated by Django 2.2.11 on 2020-07-10 05:15

from django.db import migrations, models
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TalkTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Talk about labels')),
            ],
            options={
                'verbose_name': 'Talk about labels',
                'verbose_name_plural': 'Talk about labels',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TalkContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', mdeditor.fields.MDTextField(verbose_name='Talk about the body')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation time')),
                ('status', models.TextField(choices=[('y', 'Public'), ('n', 'Private')], default='y', verbose_name='Publication Status')),
                ('tag', models.ManyToManyField(to='myzone.TalkTags', verbose_name='Talk about tags')),
            ],
            options={
                'verbose_name': 'Talk about content',
                'verbose_name_plural': 'Talk about content',
                'ordering': ['-created_time'],
            },
        ),
    ]
