# Generated by Django 2.2.11 on 2020-07-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamExpert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('role', models.CharField(max_length=200, verbose_name='Role')),
                ('about', models.TextField(verbose_name='About')),
                ('cover', models.ImageField(upload_to='portfolio', verbose_name='Upload cover')),
                ('facebook', models.URLField(blank=True, max_length=250, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, max_length=250, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, max_length=250, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, max_length=250, verbose_name='Linkedin')),
                ('github', models.URLField(blank=True, max_length=250, verbose_name='Github')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='Creation time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='Modified time')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('words', models.PositiveIntegerField(default=0, verbose_name='Word count')),
                ('status', models.CharField(choices=[('p', 'Article Page'), ('c', 'Tutorial page'), ('d', 'Draft Box'), ('r', 'Recycle Bin')], default='p', max_length=1, verbose_name='Article status')),
                ('stick', models.CharField(choices=[('y', 'Sticky'), ('n', 'Do not top')], default='n', max_length=1, verbose_name='Whether sticky')),
            ],
            options={
                'verbose_name': 'Add TeamExpert',
                'verbose_name_plural': 'Add TeamExpert',
                'ordering': ['-created_time'],
            },
        ),
    ]
