# Generated by Django 2.2.11 on 2020-03-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QiniuTokenRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(help_text='Requester IP', verbose_name='Requester IP')),
                ('token', models.CharField(help_text='token', max_length=512, verbose_name='token')),
                ('use_type', models.CharField(choices=[('comment', 'comment')], help_text='use type', max_length=15, verbose_name='use type')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='send time', verbose_name='send time')),
            ],
            options={
                'verbose_name': 'Qiniu Cloud Requests Token',
                'verbose_name_plural': 'Qiniu Cloud Requests Token',
            },
        ),
    ]
