# Generated by Django 2.2.11 on 2020-04-04 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrolikeunlike', '0002_auto_20200403_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrolike',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'agropost'), ('model', 'Agropostinfo')), models.Q(('app_label', 'agromarket'), ('model', 'Agromarketinfo')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Content type'),
        ),
    ]
