# Generated by Django 2.2.11 on 2020-08-04 06:52

import careers.file_validation_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='audio',
            field=careers.file_validation_field.ContentTypeRestrictedFileField(default='', help_text='Audio file auto generated .mp3', upload_to='articel/%Y/%m/%d/audio', verbose_name='Article Audio'),
            preserve_default=False,
        ),
    ]
