# Generated by Django 2.2.11 on 2020-06-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200601_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Is Removed'),
        ),
    ]
