# Generated by Django 2.0.10 on 2020-02-01 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_remove_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('content', mdeditor.fields.MDTextField(verbose_name='content')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='Modified time')),
                ('slug', models.SlugField(default='looks-like-this', max_length=200, unique=True, verbose_name='Slug')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('words', models.PositiveIntegerField(default=0, verbose_name='Word count')),
                ('status', models.CharField(choices=[('p', 'Article Page'), ('c', 'Tutorial page'), ('d', 'Draft Box'), ('r', 'Recycle Bin')], default='p', max_length=1, verbose_name='Article status')),
                ('stick', models.CharField(choices=[('y', 'Sticky'), ('n', 'Do not top')], default='n', max_length=1, verbose_name='Whether sticky')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Add Portfolio',
                'verbose_name_plural': 'Add Portfolio',
                'ordering': ['-created_time'],
            },
        ),
    ]
