# Generated by Django 2.0.10 on 2020-02-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200201_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='cover',
            field=models.ImageField(blank=True, upload_to='movies', verbose_name='Upload cover'),
        ),
    ]
