# Generated by Django 2.0.10 on 2020-02-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_portfolio_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Summary'),
        ),
    ]
