# Generated by Django 2.0.10 on 2020-02-02 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_teamexpert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='AppliedOn')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('description', mdeditor.fields.MDTextField(verbose_name='description')),
                ('location', models.CharField(max_length=150, verbose_name='Location')),
                ('jobtype', models.CharField(choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship')], max_length=10, verbose_name='JobType')),
                ('last_date', models.DateTimeField(verbose_name='LastDate')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreatedAt')),
                ('filled', models.BooleanField(default=False, verbose_name='Filled')),
                ('salary', models.IntegerField(blank=True, default=0, verbose_name='Salary')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
            ],
            options={
                'verbose_name': 'Add Job',
                'verbose_name_plural': 'Add Job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Job Category',
                'verbose_name_plural': 'Job Category',
            },
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='created_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='teamexpert',
            name='created_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Creation time'),
        ),
        migrations.AddField(
            model_name='job',
            name='Jobcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.JobCategory', verbose_name='Job_Category'),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='CreatedBy'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='blog.Job', verbose_name='Job'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Applicant'),
        ),
    ]
