# Generated by Django 2.0.10 on 2020-02-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200202_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('p', 'Article Page'), ('c', 'Tutorial page'), ('d', 'Draft Box'), ('r', 'Recycle Bin')], default='p', max_length=1, verbose_name='Article status'),
        ),
        migrations.AddField(
            model_name='job',
            name='stick',
            field=models.CharField(choices=[('y', 'Sticky'), ('n', 'Do not top')], default='n', max_length=1, verbose_name='Whether sticky'),
        ),
    ]
