# Generated by Django 2.0.10 on 2020-02-02 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200202_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='LastDate'),
        ),
    ]
