# Generated by Django 2.0.10 on 2020-02-02 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200202_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
