# Generated by Django 2.0.10 on 2020-02-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateTimeField(verbose_name='LastDate'),
        ),
    ]
