# Generated by Django 2.0.10 on 2020-02-02 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200202_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cover',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='portfolio', verbose_name='Upload cover'),
            preserve_default=False,
        ),
    ]
