# Generated by Django 2.0.10 on 2020-02-02 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_job_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Jobcategory',
            new_name='jobcategory',
        ),
        migrations.AlterField(
            model_name='job',
            name='cover',
            field=models.ImageField(upload_to='job', verbose_name='Upload cover'),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='LastDate'),
        ),
    ]
