# Generated by Django 2.2.9 on 2020-02-04 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200202_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
