# Generated by Django 2.2.9 on 2020-02-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='cover',
            field=models.ImageField(blank=True, upload_to='portfolio', verbose_name='Upload cover'),
        ),
    ]
