# Generated by Django 2.2.11 on 2020-06-03 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Article Category',
                'verbose_name_plural': 'Article Category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Label name')),
            ],
            options={
                'verbose_name': 'Article tags',
                'verbose_name_plural': 'Article tags',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('body', mdeditor.fields.MDTextField(verbose_name='body')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='Creation time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='Modified time')),
                ('excerpt', models.CharField(blank=True, max_length=200, verbose_name='Summary')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('words', models.PositiveIntegerField(default=0, verbose_name='Word count')),
                ('status', models.CharField(choices=[('p', 'Article Page'), ('c', 'Tutorial page'), ('d', 'Draft Box'), ('r', 'Recycle Bin')], default='p', max_length=1, verbose_name='Article status')),
                ('stick', models.CharField(choices=[('y', 'Sticky'), ('n', 'Do not top')], default='n', max_length=1, verbose_name='Whether sticky')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Category', verbose_name='Article Category')),
                ('tag', models.ManyToManyField(blank=True, to='blogs.Tag', verbose_name='Tag type')),
            ],
            options={
                'verbose_name': 'Add article',
                'verbose_name_plural': 'Add article',
                'ordering': ['-created_time'],
            },
        ),
    ]
