# Generated by Django 2.2.11 on 2020-07-10 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified time')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio.BaseModel')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('about', models.TextField(verbose_name='About')),
                ('cover', models.ImageField(blank=True, upload_to='portfolio', verbose_name='Upload cover')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('words', models.PositiveIntegerField(default=0, verbose_name='Word count')),
                ('status', models.CharField(choices=[('p', 'Article Page'), ('c', 'Tutorial page'), ('d', 'Draft Box'), ('r', 'Recycle Bin')], default='p', max_length=1, verbose_name='Article status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Add Portfolio',
                'verbose_name_plural': 'Add Portfolio',
                'ordering': ['-created_at'],
            },
            bases=('portfolio.basemodel',),
        ),
    ]
