# Generated by Django 2.2.11 on 2020-05-20 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Job Category',
                'verbose_name_plural': 'Job Category',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('cover', models.ImageField(upload_to='job', verbose_name='Upload cover')),
                ('description', mdeditor.fields.MDTextField(verbose_name='description')),
                ('location', models.CharField(max_length=150, verbose_name='Location')),
                ('jobtype', models.CharField(choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship')], max_length=10, verbose_name='JobType')),
                ('last_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='LastDate')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreatedAt')),
                ('filled', models.BooleanField(default=False, verbose_name='Filled')),
                ('salary', models.IntegerField(blank=True, default=0, verbose_name='Salary')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('status', models.CharField(choices=[('p', 'Article Page'), ('c', 'Tutorial page'), ('d', 'Draft Box'), ('r', 'Recycle Bin')], default='p', max_length=1, verbose_name='Article status')),
                ('stick', models.CharField(choices=[('y', 'Sticky'), ('n', 'Do not top')], default='n', max_length=1, verbose_name='Whether sticky')),
                ('jobcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.JobCategory', verbose_name='Job_Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='CreatedBy')),
            ],
            options={
                'verbose_name': 'Add Job',
                'verbose_name_plural': 'Add Job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='AppliedOn')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='careers.Job', verbose_name='Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Applicant')),
            ],
        ),
    ]
