# Generated by Django 2.2.11 on 2020-06-08 10:04

import careers.file_validation_field
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='slug',
        ),
        migrations.AddField(
            model_name='job',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified time'),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='create time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified time'),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create time'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ApplicantDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('fullname', models.CharField(max_length=100, verbose_name='Fullname')),
                ('cover', models.ImageField(upload_to='job/coverphoto/', verbose_name='Upload cover')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('tenth_percent', models.FloatField(verbose_name='Tenth Percent')),
                ('puc_or_diploma', models.CharField(choices=[('p', 'Puc'), ('d', 'Diploma')], default='d', max_length=1, verbose_name='College')),
                ('puc_or_diploma_marks', models.FloatField(verbose_name='Puc or Diploma Marks')),
                ('board', models.CharField(max_length=60, verbose_name='Board')),
                ('degree_college', models.CharField(max_length=50, verbose_name='Degree College')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('university', models.CharField(max_length=50, verbose_name='University')),
                ('branch', models.CharField(max_length=50, verbose_name='Branch')),
                ('grade_or_percent', models.CharField(choices=[('g', 'Grade'), ('p', 'Percentage')], default='g', max_length=1, verbose_name='Degree Marks Format')),
                ('degree_marks', models.FloatField(verbose_name='Degree Marks')),
                ('github', models.URLField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message="Url must be entered in the format: 'https://github.com/xxx or https://www.github.com/xxx '. Up to 15 digits allowed.", regex='/^(https?:\\/\\/)?(www\\.)?github.com\\/[a-zA-Z0-9(\\.\\?)?]/')], verbose_name='Github Url')),
                ('linkedin', models.URLField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: 'https://linkedin.com/in/xxx or https://www.linkedin.com/in/xxx'. Up to 15 digits allowed.", regex='/^(https?:\\/\\/)?(www\\.)?linkedin.com\\/[a-zA-Z0-9(\\.\\?)?]/')], verbose_name='Linkedin Url')),
                ('resume', careers.file_validation_field.ContentTypeRestrictedFileField(help_text='Attach resume with .docx or .pdf format', upload_to='documents/%Y/%m/%d', verbose_name='Resume')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.Job', verbose_name='Job Selected')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
