# Generated by Django 2.2.11 on 2020-06-17 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_auto_20200608_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vacancies',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Vaccencies'),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='github',
            field=models.URLField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message="Url must be entered in the format: 'https://github.com/xxx or https://www.github.com/xxx '. Up to 15 digits allowed.", regex='^https:\\/\\/[a-z]{2,3}\\.github\\.com\\/.*$')], verbose_name='Github Url'),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='linkedin',
            field=models.URLField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: 'https://linkedin.com/in/xxx or https://www.linkedin.com/in/xxx'. Up to 15 digits allowed.", regex='^https:\\/\\/[a-z]{2,3}\\.linkedin\\.com\\/.*$')], verbose_name='Linkedin Url'),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobtype',
            field=models.CharField(choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship'), ('4', 'Remote'), ('5', 'Freelance')], max_length=10, verbose_name='JobType'),
        ),
    ]
