# Generated by Django 2.2.11 on 2020-06-17 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('careers', '0003_auto_20200617_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdetails',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='CreatedBy'),
            preserve_default=False,
        ),
    ]
