# Generated by Django 2.2.11 on 2020-07-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commands',
            options={'verbose_name': 'Commands', 'verbose_name_plural': 'Commands'},
        ),
        migrations.AlterModelOptions(
            name='emailsendlog',
            options={'ordering': ['-created_time'], 'verbose_name': 'Email Sendlog', 'verbose_name_plural': 'Email Sendlog'},
        ),
        migrations.AlterField(
            model_name='commands',
            name='command',
            field=models.CharField(max_length=2000, verbose_name='command'),
        ),
        migrations.AlterField(
            model_name='commands',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='createdaAt'),
        ),
        migrations.AlterField(
            model_name='commands',
            name='describe',
            field=models.CharField(max_length=300, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='commands',
            name='last_mod_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='commands',
            name='title',
            field=models.CharField(max_length=300, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='emailsendlog',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='emailsendlog',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='emailsendlog',
            name='emailto',
            field=models.CharField(max_length=300, verbose_name='Emailto'),
        ),
        migrations.AlterField(
            model_name='emailsendlog',
            name='send_result',
            field=models.BooleanField(default=False, verbose_name='send result'),
        ),
        migrations.AlterField(
            model_name='emailsendlog',
            name='title',
            field=models.CharField(max_length=2000, verbose_name='title'),
        ),
    ]
