name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: puneethreddyhc
    - name: agroapp
      run: docker build . --file Dockerfile --tag agroapp:$(date +%s)
